"""Semantic versioning helpers for the CLI orchestrator."""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Mapping, Optional, Sequence

from modules.utils import helpers
from modules.utils.logger import get_logger

SEMVER_PATTERN = re.compile(r"^(\d+)\.(\d+)\.(\d+)$")


class VersioningError(RuntimeError):
    """Raised when semantic version operations fail."""


@dataclass(frozen=True)
class ReleasePlan:
    """Structured data about a planned release tag and its notes."""

    version: str
    notes_path: Path
    notes: str


class VersionManager:
    """Manage semantic version tags and release note artifacts."""

    def __init__(
        self,
        *,
        slice_id: str = "05",
        phase: str = "build",
        artifact_root: Optional[Path] = None,
        logger_name: str = "release.orchestrator.versioning",
    ) -> None:
        self.slice_id = slice_id
        self.phase = phase
        self._artifact_root = artifact_root or helpers.artifact_path(slice_id)
        helpers.ensure_directory(self._artifact_root)
        self._logger = get_logger(logger_name)

    # -- public API -----------------------------------------------------
    def plan_release(
        self,
        *,
        release_type: str,
        current_tag: Optional[str] = None,
        fix_version: str,
        highlights: Sequence[str] = (),
        metadata: Optional[Mapping[str, object]] = None,
        timestamp: Optional[str] = None,
    ) -> ReleasePlan:
        """Compute the next version tag and persist release notes."""

        target_tag = self.bump_version(current_tag, release_type)
        notes = self.build_release_notes(
            version=target_tag,
            fix_version=fix_version,
            highlights=highlights,
            metadata=metadata or {},
        )
        sanitized = self._mask_sensitive(notes)
        notes_path = self.write_release_notes(sanitized, timestamp=timestamp)
        self._logger.info(
            "Release plan prepared",
            extra={
                "slice_id": self.slice_id,
                "phase": self.phase,
                "version": target_tag,
                "notes_path": str(notes_path),
            },
        )
        return ReleasePlan(version=target_tag, notes_path=notes_path, notes=sanitized)

    @staticmethod
    def bump_version(current_tag: Optional[str], release_type: str) -> str:
        """Return the next semantic version string."""

        release_type = release_type.lower()
        if release_type not in {"major", "minor", "patch"}:
            raise VersioningError(f"Unsupported release type: {release_type}")

        if current_tag:
            match = SEMVER_PATTERN.match(current_tag)
            if not match:
                raise VersioningError(f"Invalid semantic version: {current_tag}")
            major, minor, patch = map(int, match.groups())
        else:
            major = minor = patch = 0

        if release_type == "major":
            major += 1
            minor = 0
            patch = 0
        elif release_type == "minor":
            minor += 1
            patch = 0
        else:
            patch += 1

        return f"{major}.{minor}.{patch}"

    def build_release_notes(
        self,
        *,
        version: str,
        fix_version: str,
        highlights: Sequence[str],
        metadata: Mapping[str, object],
    ) -> str:
        """Build Markdown release notes for the provided version."""

        highlight_lines = "\n".join(f"- {item}" for item in highlights) or "- No additional highlights captured."
        metadata_lines = "\n".join(
            f"| {key} | {value} |" for key, value in sorted(metadata.items())
        )
        if metadata_lines:
            metadata_table = "\n".join(
                ["| Field | Value |", "| --- | --- |", metadata_lines]
            )
        else:
            metadata_table = "| Field | Value |\n| --- | --- |\n| Notes | Metadata not provided |"

        notes = "\n".join(
            [
                f"# Release Plan for {fix_version}",
                "",
                f"## Proposed Tag: `{version}`",
                "",
                "## Highlights",
                highlight_lines,
                "",
                "## Metadata",
                metadata_table,
                "",
                "_Generated by Release Intelligence Slice 05 orchestrator._",
            ]
        )
        return notes

    def write_release_notes(self, content: str, *, timestamp: Optional[str] = None) -> Path:
        """Persist release notes beneath the slice artifact directory."""

        timestamp = timestamp or helpers.timestamp_for_filename()
        releases_dir = helpers.ensure_directory(self._artifact_root / "releases")
        path = releases_dir / f"version_tag_notes_{timestamp}.md"
        path.write_text(content, encoding="utf-8")
        return path

    # -- internal helpers -----------------------------------------------
    def _mask_sensitive(self, value: str) -> str:
        masked = value
        for secret in self._sensitive_values():
            if secret:
                masked = masked.replace(secret, "***")
        return masked

    def _sensitive_values(self) -> Iterable[str]:
        return [
            os.getenv("JIRA_SECRET", ""),
            os.getenv("SSL_CERT_PATH", ""),
        ]

